import type { AdmissionFormValues } from "@/lib/schemas/admission-form";
import type { AdmissionApplication } from "@/lib/types/admissions";

export function applicationToFormValues(app: AdmissionApplication): AdmissionFormValues {
  return {
    firstName: app.student.firstName,
    middleName: app.student.middleName ?? "",
    lastName: app.student.lastName,
    preferredName: app.student.preferredName ?? "",
    dob: app.student.dob,
    gender: app.student.gender,
    bloodGroup: app.student.bloodGroup ?? "",
    nationality: app.student.nationality || "Indian",
    religion: app.student.religion ?? "",
    category: app.student.category ?? "",
    motherTongue: app.student.motherTongue ?? "",
    photoUrl: app.student.photoUrl ?? "",
    appliedClassId: app.appliedClassId,
    appliedSectionPreference: app.appliedSectionPreference ?? "",
    admissionType: app.admissionType,
    session: app.session,
    line1: app.address.line1 ?? "",
    line2: app.address.line2 ?? "",
    city: app.address.city ?? "",
    state: app.address.state ?? "",
    postalCode: app.address.postalCode ?? "",
    country: app.address.country || "India",
    guardians: app.guardians.map((g) => ({
      id: g.id,
      role: g.role,
      firstName: g.firstName,
      lastName: g.lastName,
      relationship: g.relationship ?? "",
      occupation: g.occupation ?? "",
      organization: g.organization ?? "",
      email: g.contact.email ?? "",
      phone: g.contact.phone,
      alternatePhone: g.contact.alternatePhone ?? "",
      isPrimary: g.isPrimary,
      isEmergencyContact: g.isEmergencyContact,
      authorizedPickup: g.authorizedPickup,
      communicationPreference: g.communicationPreference,
    })),
    previousSchool: app.previousSchool ?? { schoolName: "", board: "", lastClassCompleted: "", yearOfLeaving: "", reasonForLeaving: "", tcNumber: "" },
    academicDetails: app.academicDetails ?? { preferredSecondLanguage: "", extracurricularInterests: "", specialNeeds: "", siblingStudentId: "" },
    medicalInfo: app.medicalInfo ?? { allergies: "", conditions: "", medications: "", emergencyContact: "", emergencyPhone: "", physicianName: "" },
    transport: { required: app.transport.required, routeId: app.transport.routeId ?? "", pickupStop: app.transport.pickupStop ?? "" },
    hostel: { required: app.hostel.required, blockPreference: app.hostel.blockPreference },
    interview: { preferredSlot: "", preferredMode: undefined },
    feeDetails: { applicationFeePaid: app.feeDetails.applicationFeePaid, applicationFeeReference: app.feeDetails.applicationFeeReference ?? "" },
  };
}

export function formValuesToApplicationPatch(values: AdmissionFormValues): Partial<AdmissionApplication> {
  return {
    student: {
      firstName: values.firstName,
      middleName: values.middleName || undefined,
      lastName: values.lastName,
      preferredName: values.preferredName || undefined,
      dob: values.dob,
      gender: values.gender,
      bloodGroup: values.bloodGroup || undefined,
      nationality: values.nationality,
      religion: values.religion || undefined,
      category: values.category || undefined,
      motherTongue: values.motherTongue || undefined,
      photoUrl: values.photoUrl || undefined,
    },
    appliedClassId: values.appliedClassId,
    appliedSectionPreference: values.appliedSectionPreference || undefined,
    admissionType: values.admissionType,
    session: values.session,
    address: { line1: values.line1, line2: values.line2 || undefined, city: values.city, state: values.state, postalCode: values.postalCode, country: values.country },
    guardians: values.guardians.map((g) => ({
      id: g.id,
      role: g.role,
      firstName: g.firstName,
      lastName: g.lastName,
      relationship: g.relationship || undefined,
      occupation: g.occupation || undefined,
      organization: g.organization || undefined,
      contact: { email: g.email || undefined, phone: g.phone, alternatePhone: g.alternatePhone || undefined },
      isPrimary: g.isPrimary,
      isEmergencyContact: g.isEmergencyContact,
      authorizedPickup: g.authorizedPickup,
      communicationPreference: g.communicationPreference,
    })),
    previousSchool: values.previousSchool?.schoolName
      ? {
          schoolName: values.previousSchool.schoolName,
          board: values.previousSchool.board || undefined,
          lastClassCompleted: values.previousSchool.lastClassCompleted || "",
          yearOfLeaving: values.previousSchool.yearOfLeaving || undefined,
          reasonForLeaving: values.previousSchool.reasonForLeaving || undefined,
          tcNumber: values.previousSchool.tcNumber || undefined,
        }
      : undefined,
    academicDetails: values.academicDetails,
    medicalInfo: values.medicalInfo,
    transport: { required: values.transport.required, routeId: values.transport.routeId || undefined, pickupStop: values.transport.pickupStop || undefined },
    hostel: { required: values.hostel.required, blockPreference: values.hostel.blockPreference },
    feeDetails: { applicationFeePaid: values.feeDetails.applicationFeePaid, applicationFeeReference: values.feeDetails.applicationFeeReference || undefined },
  };
}
